In [1]:
#Machine Learning 

#label - data that i want to guess

#feature(s) - the input variable(s) it can be several 

#labelled - with label and feature
#unlabelled - without label, only input

#model - system that defines the rel. between the feature and label
    #Training phase - show how it works 

    



In [2]:
import numpy as np

array = np.array([[1, 2, 3], [1, 2, 3]])
print(array)

[[1 2 3]
 [1 2 3]]


In [9]:
list0 = [1,2,3]
list1 = list0.copy()
list1[0] = 55
print(list1)
print(list0)

[55, 2, 3]
[1, 2, 3]


In [11]:
array = np.array([1, 2, 3])
arr0 = array.copy()
arr0[1] = 50
print(array)
print(arr0)

[1 2 3]
[ 1 50  3]


In [14]:
array = np.array([1, 2, 3, 4, 5, 6])
print(array.reshape((3,2)))

[[1 2]
 [3 4]
 [5 6]]


In [16]:
array = np.array([1, 2, 3, 4, 5, 6])
print(array.reshape((2,3)))

[[1 2 3]
 [4 5 6]]


In [23]:
array = np.array([1, 2, 3, 4, 5, 6])
print(array.reshape((6,-1)))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [5]:
array0 = np.array([1, 2, 3, 4, 5, 6])
array0= array0.reshape((-1,1))
array1 = np.array([7, 8, 9, 10, 11, 12])
array1 = array1.reshape((-1,1))
print("-"*20)

print(np.hstack([array0, array1]))

--------------------
[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [29]:
array = np.array([1, 5, 9, 31, 45, 78])
array2 = array.copy()
print(array2.reshape((-1,2)))

[[ 1  5]
 [ 9 31]
 [45 78]]
