In [1]:
import numpy as np
import sklearn.linear_model as skmod
import sklearn.preprocessing as skprepro
import matplotlib.pyplot as plt

arr1 = [6, 10, 2, 3, 4, 0, 7, 8, 9, 1]
arr2 = [130, 21, 43, 76, 105, 3, 167, 162, 91, 15]

In [2]:
arr_x = np.array(arr1).reshape(-1,1)
arr_y = np.array(arr2).reshape(-1,1)

In [5]:
poly2 = skprepro.PolynomialFeatures(degree = 8, include_bias = False)

In [8]:
arr_x_poly = poly2.fit_transform(arr_x)
# print(arr_x_poly)
model = skmod.LinearRegression().fit(arr_x_poly, arr_y)
print(model.coef_)

[[ 4.64288632e+01 -8.12079635e+01  6.74485406e+01 -2.38710248e+01
   4.20411268e+00 -3.74085602e-01  1.49834019e-02 -1.72233273e-04]]


In [9]:
a = [22, 85, 96, 81, 68, 97, 29, 61, 73, 86]
b = [1489022, 1073767, 1975250, 1493073, 1063635, 1017921, 1206827, 1217274, 1933018, 1325618]
c = [-99.67, -99.37, -99.08, -99.54, -99.8, -99.21, -99.73, -99.78, -99.6, -99.48]
d = [-182, -254.3,  -71  , -172, -261 , -262, -237, -231, -85, -204]

In [16]:
data_x1 = np.array(a).reshape(-1,1)
data_x2 = np.array(b).reshape(-1,1)
data_x3 = np.array(c).reshape(-1,1)
data_x4 = np.array(d).reshape(-1,1)

In [17]:
scaler = skprepro.StandardScaler()

data_x = np.hstack([data_x1.reshape(-1,1), data_x2.reshape(-1,1),data_x3.reshape(-1,1), data_x4.reshape(-1,1)])
print(data_x)

[[ 2.200000e+01  1.489022e+06 -9.967000e+01 -1.820000e+02]
 [ 8.500000e+01  1.073767e+06 -9.937000e+01 -2.543000e+02]
 [ 9.600000e+01  1.975250e+06 -9.908000e+01 -7.100000e+01]
 [ 8.100000e+01  1.493073e+06 -9.954000e+01 -1.720000e+02]
 [ 6.800000e+01  1.063635e+06 -9.980000e+01 -2.610000e+02]
 [ 9.700000e+01  1.017921e+06 -9.921000e+01 -2.620000e+02]
 [ 2.900000e+01  1.206827e+06 -9.973000e+01 -2.370000e+02]
 [ 6.100000e+01  1.217274e+06 -9.978000e+01 -2.310000e+02]
 [ 7.300000e+01  1.933018e+06 -9.960000e+01 -8.500000e+01]
 [ 8.600000e+01  1.325618e+06 -9.948000e+01 -2.040000e+02]]


In [18]:
scaler_f = scaler.fit_transform(data_x)
# data_x_stan = scaler_f.transform(data_x)
print(scaler_f)
# print(scaler_f.transform([[3, 3]]))

[[-1.93765385  0.33481781 -0.62382688  0.21079983]
 [ 0.61615771 -0.93512067  0.67581245 -0.88330123]
 [ 1.06206131  1.82180687  1.93213047  1.89054004]
 [ 0.45401094  0.34720663 -0.06064984  0.36212778]
 [-0.07296604 -0.96610649 -1.18700392 -0.98469095]
 [ 1.10259801 -1.10590966  1.36895343 -0.99982374]
 [-1.65389701 -0.52819477 -0.88375474 -0.62150388]
 [-0.35672288 -0.49624561 -1.1003613  -0.53070711]
 [ 0.12971741  1.6926524  -0.3205777   1.67868091]
 [ 0.6566944  -0.16490652  0.19927803 -0.12212165]]
